// Minimal single-page PDF builder (no external deps) — used as placeholder
// content for the `downloads` collection's required `file` upload field.

function pdfEscape(text: string): string {
  return text.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)')
}

export function createPlaceholderPdf(title: string, note: string): Buffer {
  const objects: string[] = []

  objects.push('<< /Type /Catalog /Pages 2 0 R >>')
  objects.push('<< /Type /Pages /Kids [3 0 R] /Count 1 >>')
  objects.push(
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>',
  )
  objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>')

  const lines = [
    `BT /F1 20 Tf 72 700 Td (${pdfEscape(title)}) Tj ET`,
    `BT /F1 12 Tf 72 670 Td (${pdfEscape(note)}) Tj ET`,
    'BT /F1 12 Tf 72 650 Td (This placeholder file was generated by the demo seed script.) Tj ET',
  ]
  const stream = lines.join('\n')
  objects.push(`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`)

  const header = '%PDF-1.4\n'
  let body = header
  const offsets: number[] = [0]

  objects.forEach((obj, i) => {
    offsets.push(Buffer.byteLength(body))
    body += `${i + 1} 0 obj\n${obj}\nendobj\n`
  })

  const xrefOffset = Buffer.byteLength(body)
  let xref = `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`
  for (let i = 1; i <= objects.length; i++) {
    xref += `${String(offsets[i]).padStart(10, '0')} 00000 n \n`
  }
  body += xref
  body += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`

  return Buffer.from(body, 'ascii')
}
